#  network layout for wiretap testing
#
# ┌──────────┐
# │ server   │
# │          │
# │ 10.1.0.2 │
# │ fd:1::2  ├┬───────────────────────┐
# ├──────────┼│ exposed network       │
# ├──────────┼│ 10.1.0.0/16,fd:1::/64 │
# │ 10.1.0.3 ├┴───────────────────────┘
# │ fd:1::3  │
# │          │
# │ agent    │
# │          │
# │ 10.2.0.3 │
# │ fd:2::3  ├┬───────────────────────┐
# ├──────────┼│ target network        │
# ├──────────┼│ 10.2.0.0/16,fd:2::/64 │
# │ 10.2.0.4 ├┴───────────────────────┘
# │ fd:2::4  │
# │          │
# │ target   │
# │          │
# │ 10.3.0.4 │
# │ fd:3::4  ├┬───────────────────────┐
# ├──────────┼│ target2 network       │
# ├──────────┼│ 10.3.0.0/16,fd:3::/64 │
# │ 10.3.0.5 ├┴───────────────────────┘
# │ fd:3::5  │
# │          │
# │ target2  │
# └──────────┘

services:
  server:
    # build: 
    #   context: .
    #   dockerfile: wiretap.Dockerfile
    image: wiretap:latest
    networks:
      exposed:
        ipv4_address: 10.1.0.2
        ipv6_address: fd:1::2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
    - DISPLAY=host.docker.internal:0
  agent: 
    depends_on: 
      - server 
    build: 
      context: .
      dockerfile: wiretap-agent.Dockerfile
    image: wiretap-agent:latest
    networks:
      exposed:
        ipv4_address: 10.1.0.3
        ipv6_address: fd:1::3
      target:
        ipv4_address: 10.2.0.3
        ipv6_address: fd:2::3
    environment:
      - AGENT_PRIVATE_KEY=4O6c5RatRHKQuhBGATy/Z5gTDsrgqdXEVM/ugJUtwmo=
      - APIIRO_PUBLIC_KEY=4cw7P2SkpcIERT3fOSBSeq+h0hRm+qXv2UPvVw3bYwI=
      - TUNNEL_SUBNET=172.16.0
      - APIIRO_ENDPOINT=10.1.0.2:51820
      - MAPPING_PREFIX=10.100.0
      - MAPPING_HOSTS=10.2.0.4,example.com:443
      - CONFIG_ENDPOINT=https://34.149.164.82/rest-api/v1.0/broker/configuration
      - SKIP_SSL_VERIFY=true
      - CONFIG_TOKEN=xxxAccessTokenxxx
      - VERBOSE_LOGS=true
  target:
    depends_on: 
      - agent 
    image: wiretap:latest
    networks:
      target:
        ipv4_address: 10.2.0.4
        ipv6_address: fd:2::4
      # target2:
      #   ipv4_address: 10.3.0.4
      #   ipv6_address: fd:3::4
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
  # target2:
  #   depends_on: 
  #     - client 
  #   image: wiretap:latest
  #   networks:
  #     target2:
  #       ipv4_address: 10.3.0.5
  #       ipv6_address: fd:3::5
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   sysctls:
  #     - net.ipv6.conf.all.disable_ipv6=0


networks:
  exposed:
    enable_ipv6: true
    driver: bridge
    name: exposed
    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1
        - subnet: fd:1::/64
          gateway: fd:1::1
  target:
    enable_ipv6: true
    driver: bridge
    name: target 
    ipam:
      config:
        - subnet: 10.2.0.0/16
          gateway: 10.2.0.1
        - subnet: fd:2::/64
          gateway: fd:2::1
  # target2:
  #   enable_ipv6: true
  #   driver: bridge
  #   name: target2
  #   ipam:
  #     config:
  #       - subnet: 10.3.0.0/16
  #         gateway: 10.3.0.1
  #       - subnet: fd:3::/64
  #         gateway: fd:3::1
