#!/bin/sh

WIRETAP_RELAY_INTERFACE_PRIVATEKEY=$AGENT_PRIVATE_KEY \
WIRETAP_RELAY_PEER_PUBLICKEY=$APIIRO_PUBLIC_KEY \
WIRETAP_RELAY_PEER_ENDPOINT=$APIIRO_ENDPOINT \
WIRETAP_SIMPLE=true \
./wiretap serve